### ISSUE TITLE
odd error in ANDROID N(7)

### ISSUE THREAD

**Issue by xlen** [kbox4/source#13] opened 2017-06-27 22:00 UTC
Tried it many times, still the same error, no way to bypass it without rewritting the installer

HWVNS-H:/ $ cd /data/data/jackpal.androidterm
d/kbox4-install-base-arm > kbox4-install-base             <
hmod 755 kbox4-install-base                               <
/kbox4-install-base                                       <
CANNOT LINK EXECUTABLE "./kbox4-install-base": cannot find verneed/verdef for version index=2 referenced by symbol "__sF" at "/data/data/jackpal.androidterm/kbox4-install-base"
Aborted
kbox4-install-base                                        <
/system/bin/sh: .kbox4-install-base: not found
127|HWVNS-H:/data/data/jackpal.androidterm $

**Comment by xlen** [comment] 2017-06-27 22:02
Note, it was on authors recommended terminal, I'll try others

**Comment by giuliolunati** [comment] 2017-06-27 22:52
See https://github.com/kbox4/source/issues/10

**Comment by kevinboone** [comment] 2017-06-28 06:43
I've put up a version of the installer (for ARM) here:

http://kevinboone.net/kbox4-install-base-not-cleaned

Folks with this problem could try using this version instead of kbox4-install-base-arm. I could put up an x86 version, if necessary. We still need a longer-term solution to this problem, that does not involve maintaining separate distributions, but I have no idea at present what form it will take.

**Comment by kevinboone** [comment] 2017-06-28 06:45
Closing as duplicate of #10

**Closed as completed** 2017-06-28 06:44 UTC
